# Generated by Django 3.2.13 on 2022-06-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20220621_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_activity_book', models.BooleanField(default=False)),
                ('hide_course_book', models.BooleanField(default=False)),
                ('hide_story_book', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
