# Generated by Django 3.2.13 on 2022-06-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='media/profile_picture'),
        ),
    ]
