# Generated by Django 3.2.13 on 2022-07-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_activity_book',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_course_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_story_book',
            field=models.BooleanField(default=False),
        ),
    ]
